source "https://rubygems.org"

gem "jekyll", "~> 3.8.6"

group :jekyll_plugins do
  gem 'jekyll-feed', '~> 0.13.0'
  gem 'jekyll-postcss', '~> 0.2.2'
  gem 'jekyll-purgecss', '~> 0.3.0'
  gem 'jekyll-seo-tag', '~> 2.6', '>= 2.6.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?
